name: simple_month_year_picker
description: Simple to use month/year picker for your apps with highly customisable options.
version: 1.1.0
homepage: https://github.com/sivaprasadnk/SimpleMonthYearPicker

environment:
  sdk: ">=2.16.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

